### ISSUE TITLE
edx_lint command no longer installed

### ISSUE THREAD

**Issue by mikix** [edx/edx-lint#105]
Affects >=1.3.1

The edx_lint command wrapper around edx_lint.cmd.main no longer seems to be installed.

**Comment by nedbat** [comment]
@cpennington I can confirm this is true.  I don't see what's wrong, or how to fix it.

**Comment by cpennington** [comment]
I probably borked it in the conversion away from pbr. Maybe the entrypoints configuration in setup.cfg needs to be in a slightly different place/format?

**Comment by nedbat** [comment]
It worked when you first moved it from setup.py.  Then more things in setup.cfg broke it somehow, or something.

**Comment by nedbat** [comment]
1.4.1 has the fix.
