### ISSUE TITLE
Suggestion: Bump edx-lint major version when upgrading to stricter pylint

### ISSUE THREAD

**Issue by kdmccormick** [edx/edx-lint#107]
1.3.0 used pylint 1.7.6, while 1.4.1 uses pylint 2+

Pylint 2+ features some errors and warnings that did not appear in pylint 1.7.6. This is good an alll, but it's a breaking change for repos that require a 10/10 pylint score on PRs. Per semver, we should bump the edx-lint major version in the future.

**Comment by nedbat** [comment]
I'm fine with bumping the major on edx_lint when we bump the major on pylint.  But keep in mind that Pylint 2.3 could also have warnings that Pylint 2.2 didn't have.  Unless I'm mistaken, they don't bump their major version when they add new warnings.
