### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by clintonb** [edx/edx-lint#22]
- Automate tests
- Automate pushes to PyPI

**Comment by nedbat** [comment]
I would like to divide this repo into the three separate repos it should be, rather than push this one to PyPI.

**Comment by clintonb** [comment]
@nedbat do you have an ETA for that work?

**Comment by nedbat** [comment]
I don't, it's all spare-time work.  I guess it isn't a disaster to push the three-headed beast to PyPI, we can push the proper repos later when we have them.

**Comment by clintonb** [comment]
@nedbat I'm fine holding off on PyPI. I at least want to run tests. I prefer "build passed on Travis" to "It works on my machine".
